
exports.csv=
{
 "country-year/agricultural-census.csv": "data_series.\"agricultural_census\"",
 "country-year/avg-income-of-extreme-poor.csv": "data_series.\"avg_income_of_extreme_poor\"",
 "country-year/civil-reg-births.csv": "data_series.\"civil_reg_births\"",
 "country-year/civil-reg-deaths.csv": "data_series.\"civil_reg_deaths\"",
 "country-year/climate-vulnerability.csv": "data_series.\"climate_vulnerability\"",
 "country-year/dac-oda-percent-gni.csv": "data_series.\"dac_oda_percent_gni\"",
 "country-year/dac-oda-to-ldcs-pc-gni.csv": "data_series.\"dac_oda_to_ldcs_pc_gni\"",
 "country-year/depth-of-extreme-poverty-190.csv": "data_series.\"depth_of_extreme_poverty_190\"",
 "country-year/dev-coop-in-detail.csv": "data_series.\"dev_coop_in_detail\"",
 "country-year/dfis-out.csv": "data_series.\"dfis_out\"",
 "country-year/dfis-out-dev.csv": "data_series.\"dfis_out_dev\"",
 "country-year/domestic.csv": "data_series.\"domestic\"",
 "country-year/domestic-sectors.csv": "data_series.\"domestic_sectors\"",
 "country-year/educ-mis.csv": "data_series.\"educ_mis\"",
 "country-year/evi.csv": "data_series.\"evi\"",
 "country-year/fdi-out.csv": "data_series.\"fdi_out\"",
 "country-year/fdi-pp.csv": "data_series.\"fdi_pp\"",
 "country-year/fragile-states.csv": "data_series.\"fragile_states\"",
 "country-year/general-gov-health-exp.csv": "data_series.\"general_gov_health_exp\"",
 "country-year/gov-revenue-pc-gdp.csv": "data_series.\"gov_revenue_pc_gdp\"",
 "country-year/govtspend-pc.csv": "data_series.\"govtspend_pc\"",
 "country-year/grants-pct-totalrevenue.csv": "data_series.\"grants_pct_totalrevenue\"",
 "country-year/health-mis.csv": "data_series.\"health_mis\"",
 "country-year/human-hazard.csv": "data_series.\"human_hazard\"",
 "country-year/in-ha.csv": "data_series.\"in_ha\"",
 "country-year/in-oda-gross.csv": "fact.\"in_oda_gross_2012\"",
 "country-year/in-oda-net.csv": "fact.\"in_oda_net\"",
 "country-year/in-oof-gross.csv": "data_series.\"in_oof_gross\"",
 "country-year/intl-flows-donors.csv": "data_series.\"intl_flows_donors\"",
 "country-year/intl-flows-recipients.csv": "data_series.\"intl_flows_recipients\"",
 "country-year/intlresources-total.csv": "data_series.\"intlresources_total\"",
 "country-year/kenya-births-pc-skilled.csv": "data_series.\"kenya_births_pc_skilled\"",
 "country-year/kenya-electricity.csv": "data_series.\"kenya_electricity\"",
 "country-year/kenya-fertility-rate.csv": "data_series.\"kenya_fertility_rate\"",
 "country-year/kenya-improved-sani.csv": "data_series.\"kenya_improved_sani\"",
 "country-year/kenya-improved-water.csv": "data_series.\"kenya_improved_water\"",
 "country-year/kenya-paved-roads.csv": "data_series.\"kenya_paved_roads\"",
 "country-year/kenya-pc-female-know-hiv.csv": "data_series.\"kenya_pc_female_know_hiv\"",
 "country-year/kenya-pc-female-tested-hiv.csv": "data_series.\"kenya_pc_female_tested_hiv\"",
 "country-year/kenya-pc-house-malaria-nets.csv": "data_series.\"kenya_pc_house_malaria_nets\"",
 "country-year/kenya-pc-male-know-hiv.csv": "data_series.\"kenya_pc_male_know_hiv\"",
 "country-year/kenya-pc-male-tested-hiv.csv": "data_series.\"kenya_pc_male_tested_hiv\"",
 "country-year/kenya-pc-modern-contra.csv": "data_series.\"kenya_pc_modern_contra\"",
 "country-year/kenya-pc-no-contra.csv": "data_series.\"kenya_pc_no_contra\"",
 "country-year/kenya-pc-trad-contra.csv": "data_series.\"kenya_pc_trad_contra\"",
 "country-year/kenya-pop-female.csv": "data_series.\"kenya_pop_female\"",
 "country-year/kenya-pop-male.csv": "data_series.\"kenya_pop_male\"",
 "country-year/kenya-pop-pc-female.csv": "data_series.\"kenya_pop_pc_female\"",
 "country-year/kenya-pop-pc-male.csv": "data_series.\"kenya_pop_pc_male\"",
 "country-year/kenya-pop-total.csv": "data_series.\"kenya_pop_total\"",
 "country-year/kenya-pov-gap.csv": "data_series.\"kenya_pov_gap\"",
 "country-year/kenya-rural-pop.csv": "data_series.\"kenya_rural_pop\"",
 "country-year/kenya-treat-child-diarr.csv": "data_series.\"kenya_treat_child_diarr\"",
 "country-year/kenya-treat-child-respir.csv": "data_series.\"kenya_treat_child_respir\"",
 "country-year/kenya-urban-pop.csv": "data_series.\"kenya_urban_pop\"",
 "country-year/kenya-weight-below-3sd.csv": "data_series.\"kenya_weight_below_3sd\"",
 "country-year/largest-intl-flow.csv": "data_series.\"largest_intl_flow\"",
 "country-year/latest-census.csv": "data_series.\"latest_census\"",
 "country-year/latest-hh-survey.csv": "data_series.\"latest_hh_survey\"",
 "country-year/long-debt-disbursement-in.csv": "data_series.\"long_debt_disbursement_in\"",
 "country-year/long-debt-net-official-in.csv": "data_series.\"long_debt_net_official_in\"",
 "country-year/natural-hazard.csv": "data_series.\"natural_hazard\"",
 "country-year/number-of-surveys.csv": "data_series.\"number_of_surveys\"",
 "country-year/oda-capital-repayments.csv": "data_series.\"oda_capital_repayments\"",
 "country-year/oda-interest-payments.csv": "data_series.\"oda_interest_payments\"",
 "country-year/oda-per-poor-person.csv": "data_series.\"oda_per_poor_person\"",
 "country-year/oof.csv": "data_series.\"oof\"",
 "country-year/out-dac-oda-net.csv": "data_series.\"out_dac_oda_net\"",
 "country-year/out-oof-net.csv": "data_series.\"out_oof_net\"",
 "country-year/out-ssc-net.csv": "data_series.\"out_ssc_net\"",
 "country-year/poorest20pct.csv": "data_series.\"2013_p20_population\"",
 "country-year/poor-people-190.csv": "data_series.\"poor_people_190\"",
 "country-year/poverty-190.csv": "data_series.\"poverty_190\"",
 "country-year/poverty-310.csv": "data_series.\"poverty_310\"",
 "country-year/profits-pct-fdi.csv": "data_series.\"profits_pct_fdi\"",
 "country-year/remittances.csv": "data_series.\"remittances\"",
 "country-year/rems-pp.csv": "data_series.\"rems_pp\"",
 "country-year/ssc-out.csv": "data_series.\"ssc_out\"",
 "country-year/ssc-percent-gni.csv": "data_series.\"ssc_percent_gni\"",
 "country-year/stat-capacity.csv": "data_series.\"stat_capacity\"",
 "country-year/uganda-agri-percent.csv": "data_series.\"uganda_agri_percent\"",
 "country-year/uganda-anc4-coverage.csv": "data_series.\"uganda_anc4_coverage\"",
 "country-year/uganda-avg-house-size.csv": "data_series.\"uganda_avg_house_size\"",
 "country-year/uganda-central-resources.csv": "data_series.\"uganda_central_resources\"",
 "country-year/uganda-dependency-ratio.csv": "data_series.\"uganda_dependency_ratio\"",
 "country-year/uganda-deprivation-living.csv": "data_series.\"uganda_deprivation_living\"",
 "country-year/uganda-donor-educ-spend.csv": "data_series.\"uganda_donor_educ_spend\"",
 "country-year/uganda-donor-percent.csv": "data_series.\"uganda_donor_percent\"",
 "country-year/uganda-donor-resources.csv": "data_series.\"uganda_donor_resources\"",
 "country-year/uganda-dpt3-coverage.csv": "data_series.\"uganda_dpt3_coverage\"",
 "country-year/uganda-educ-percent.csv": "data_series.\"uganda_educ_percent\"",
 "country-year/uganda-finance.csv": "data_series.\"uganda_finance\"",
 "country-year/uganda-gov-spend-pp.csv": "data_series.\"uganda_gov_spend_pp\"",
 "country-year/uganda-health-funding.csv": "data_series.\"uganda_health_funding\"",
 "country-year/uganda-health-percent.csv": "data_series.\"uganda_health_percent\"",
 "country-year/uganda-health-posts.csv": "data_series.\"uganda_health_posts\"",
 "country-year/uganda-hmis.csv": "data_series.\"uganda_hmis\"",
 "country-year/uganda-household-san-cov.csv": "data_series.\"uganda_household_san_cov\"",
 "country-year/uganda-igf-resources.csv": "data_series.\"uganda_igf_resources\"",
 "country-year/uganda-ipt2-coverage.csv": "data_series.\"uganda_ipt2_coverage\"",
 "country-year/uganda-leaving-exam-perf-rate.csv": "data_series.\"uganda_leaving_exam_perf_rate\"",
 "country-year/uganda-life-expectancy.csv": "data_series.\"uganda_life_expectancy\"",
 "country-year/uganda-local-percent.csv": "data_series.\"uganda_local_percent\"",
 "country-year/uganda-overall-health.csv": "data_series.\"uganda_overall_health\"",
 "country-year/uganda-pop-dens.csv": "data_series.\"uganda_pop_dens\"",
 "country-year/uganda-poverty-headcount.csv": "data_series.\"uganda_poverty_headcount\"",
 "country-year/uganda-primary-educ-funding.csv": "data_series.\"uganda_primary_educ_funding\"",
 "country-year/uganda-primary-enrol.csv": "data_series.\"uganda_primary_enrol\"",
 "country-year/uganda-primary-sit-write.csv": "data_series.\"uganda_primary_sit_write\"",
 "country-year/uganda-primary-sit-write-gov.csv": "data_series.\"uganda_primary_sit_write_gov\"",
 "country-year/uganda-primary-stu-teach-ratio.csv": "data_series.\"uganda_primary_stu_teach_ratio\"",
 "country-year/uganda-primary-stu-teach-ratio-gov.csv": "data_series.\"uganda_primary_stu_teach_ratio_gov\"",
 "country-year/uganda-rural-safe-water.csv": "data_series.\"uganda_rural_safe_water\"",
 "country-year/uganda-rural-water-func.csv": "data_series.\"uganda_rural_water_func\"",
 "country-year/uganda-secondary-enrol.csv": "data_series.\"uganda_secondary_enrol\"",
 "country-year/uganda-secondary-sit-write.csv": "data_series.\"uganda_secondary_sit_write\"",
 "country-year/uganda-secondary-sit-write-gov.csv": "data_series.\"uganda_secondary_sit_write_gov\"",
 "country-year/uganda-secondary-stu-teach-ratio.csv": "data_series.\"uganda_secondary_stu_teach_ratio\"",
 "country-year/uganda-secondary-stu-teach-ratio-gov.csv": "data_series.\"uganda_secondary_stu_teach_ratio_gov\"",
 "country-year/uganda-tb-success.csv": "data_series.\"uganda_tb_success\"",
 "country-year/uganda-total-pop.csv": "data_series.\"uganda_total_pop\"",
 "country-year/uganda-urban-pop.csv": "data_series.\"uganda_urban_pop\"",
 "country-year/uganda-urban-rural-pop.csv": "data_series.\"uganda_urban_rural_pop\"",
 "country-year/uganda-wash-perf-score.csv": "data_series.\"uganda_wash_perf_score\"",
 "country-year/uganda-water-source-comm-func.csv": "data_series.\"uganda_water_source_comm_func\"",
 "country-year/gdp-usd-current.csv": "fact.\"gdp_usd_current\"",
 "country-year/gni-pc-usd-current.csv": "fact.\"gni_pc_usd_current\"",
 "country-year/gni-usd-current.csv": "fact.\"gni_usd_current\"",
 "country-year/income-share-bottom-20pc.csv": "fact.\"income_share_bottom_20pc\"",
 "country-year/income-share-by-quintile.csv": "fact.\"income_share_by_quintile\"",
 "country-year/life-expectancy-at-birth.csv": "fact.\"life_expectancy_at_birth\"",
 "country-year/maternal-mortality.csv": "fact.\"maternal_mortality\"",

 "country-year/oda.2014.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2014 ) sq ",
 "country-year/oda.2013.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2013 ) sq ",
 "country-year/oda.2012.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2012 ) sq ",
 "country-year/oda.2011.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2011 ) sq ",
 "country-year/oda.2010.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2010 ) sq ",
 "country-year/oda.2009.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2009 ) sq ",
 "country-year/oda.2008.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2008 ) sq ",
 "country-year/oda.2007.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2007 ) sq ",
 "country-year/oda.2006.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2006 ) sq ",
 "country-year/oda.2005.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2005 ) sq ",
 "country-year/oda.2004.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2004 ) sq ",
 "country-year/oda.2003.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2003 ) sq ",
 "country-year/oda.2002.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2002 ) sq ",
 "country-year/oda.2001.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2001 ) sq ",
 "country-year/oda.2000.csv": " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year=2000 ) sq ",
 "country-year/oda.csv"     : " ( SELECT from_di_id,to_di_id,year,sector,bundle,channel_web_id,value FROM fact.\"oda_2012\" WHERE year<=1999 ) sq ",

 "country-year/population-by-age.csv": "fact.\"population_by_age\"",
 "country-year/population-rural.csv": "fact.\"population_rural\"",
 "country-year/population-rural-urban.csv": "fact.\"population_rural_urban\"",
 "country-year/population-total.csv": "fact.\"population_total\"",
 "country-year/population-urban.csv": "fact.\"population_urban\"",
 // this is new data coming from the warehouse, so lets keep the names the same
 "country-year/warehouse/oda_per_percent_gdp.csv": "fact.\"oda_per_percent_gdp\"",
 "country-year/warehouse/oda_per_percent_gdp_excl_non_transfer.csv": "fact.\"oda_per_percent_gdp_excl_non_transfer\"",
 "country-year/warehouse/oda_per_poor_person_2012.csv": "fact.\"oda_per_poor_person_2012\"",
 "country-year/warehouse/oda_per_poor_person_excl_non_transfer_2012.csv": "fact.\"oda_per_poor_person_excl_non_transfer_2012\"",
 "country-year/warehouse/oda_per_capita_2012.csv": "fact.\"oda_per_capita_2012\"",
 "country-year/warehouse/oda_per_capita_excl_non_transfer_2012.csv": "fact.\"oda_per_capita_excl_non_transfer_2012\"",
 // new data print profile
 "country-year/warehouse/gdp_pc_usd_current_2012.csv":"fact.\"gdp_pc_usd_current_2012\"",
 // new donor data
 "country-year/warehouse/intl_outflows_donors.csv":"data_series.intl_outflows_donors",
 "country-year/warehouse/disbursement_by_region_2012.csv":"data_series.disbursement_by_region_2012",
// "country-year/warehouse/donor_bundle_2012.csv":"fact.donor_bundle_2012",
// "country-year/warehouse/loans_grants_2012.csv":"fact.loans_grants_2012",
// "country-year/warehouse/sectors_over_time_2012.csv":"fact.sectors_over_time_2012",

// new donor data from https://github.com/devinit/ddw-data/issues/220#issuecomment-251401625
// not sure if fact.dac_oda_percent_gni and data_series.dac_oda_percent_gni are the same data...
// also bubble chart seems like a useless table name, so moving this all into sub dirs by schema

 "country-year/warehouse/data_series/intl_flows_donors.csv"				:"data_series.intl_flows_donors",
 "country-year/warehouse/fact/out_oda_net_2012.csv"						:"fact.out_oda_net_2012",
 "country-year/warehouse/fact/out_debt_relief_2012.csv"					:"fact.out_debt_relief_2012",
 "country-year/warehouse/donor_profile/oda_per_capita_per_day_2012.csv"	:"donor_profile.oda_per_capita_per_day_2012",
 "country-year/warehouse/donor_profile/gni_per_capita_per_day_2012.csv"	:"donor_profile.gni_per_capita_per_day_2012",
 "country-year/warehouse/donor_profile/oda_per_capita_2012.csv"			:"donor_profile.oda_per_capita_2012",
 "country-year/warehouse/donor_profile/gni_per_capita_2012.csv"			:"donor_profile.gni_per_capita_2012",
 "country-year/warehouse/fact/dac_oda_percent_gni.csv"					:"fact.dac_oda_percent_gni",
 "country-year/warehouse/donor_profile/recipient_bundle_2012.csv"		:"donor_profile.recipient_bundle_2012",
 "country-year/warehouse/donor_profile/disbursement_by_region_2012.csv"	:"donor_profile.disbursement_by_region_2012",
 "country-year/warehouse/donor_profile/bubble_chart.csv"				:"donor_profile.bubble_chart",
 "country-year/warehouse/donor_profile/donor_bundle_2012.csv"			:"donor_profile.donor_bundle_2012",
 "country-year/warehouse/donor_profile/loans_grants_2012.csv"			:"donor_profile.loans_grants_2012",
 "country-year/warehouse/donor_profile/sectors_over_time_2012.csv"		:"donor_profile.sectors_over_time_2012",
 "country-year/warehouse/donor_profile/d14_region.csv"                  :"donor_profile.d14_region",
 "country-year/warehouse/donor_profile/d15_flow.csv"                    :"donor_profile.d15_flow",
 "country-year/warehouse/donor_profile/d15_depth_of_poverty.csv"        :"donor_profile.d15_depth_of_poverty",
// multilateral_profiles
"country-year/warehouse/multilateral_profile/oda_oof_trend.csv" : "multilateral_profile.\"oda_oof_trend_2012\"",
"country-year/warehouse/multilateral_profile/oda_oof_flow_type.csv" : "multilateral_profile.\"oda_oof_flow_type_2012\"",
"country-year/warehouse/multilateral_profile/bundle.csv" : "multilateral_profile.\"bundle_2012\"",
"country-year/warehouse/multilateral_profile/oda_regional.csv" : "multilateral_profile.\"oda_regional\"",
"country-year/warehouse/multilateral_profile/core_earmarked_oda_received.csv" : "multilateral_profile.\"core_earmarked_oda_received_2012\"",
"country-year/warehouse/multilateral_profile/core_oda_by_donor.csv" : "multilateral_profile.\"core_oda_by_donor_2012\"",
"country-year/warehouse/multilateral_profile/earmarked_oda_by_donor.csv" : "multilateral_profile.\"earmarked_oda_by_donor_2012\"",
"country-year/warehouse/multilateral_profile/master_multilateral_donor.csv" : "multilateral_profile.\"master_multilateral_donor\"",
"country-year/warehouse/multilateral_profile/mums_multilateral_donor.csv" : "multilateral_profile.\"mums_multilateral_donor\"",
"country-year/warehouse/multilateral_profile/channel.csv" : "multilateral_profile.\"channel_2012\"",
"country-year/warehouse/multilateral_profile/oda_revenue_poverty.csv" : "multilateral_profile.\"oda_revenue_poverty_2012\"",
"country-year/warehouse/multilateral_profile/purpose_by_bundle.csv" : "multilateral_profile.\"purpose_by_bundle_2012\"",
"country-year/warehouse/multilateral_profile/purpose_trend.csv" : "multilateral_profile.\"purpose_trend_2012\"",
"country-year/warehouse/multilateral_profile/recipient_by_purpose_by_di_id.csv" : "multilateral_profile.\"recipient_by_purpose_by_di_id_2012\"",
"country-year/warehouse/multilateral_profile/recipient_by_purpose_by_parent.csv" : "multilateral_profile.\"recipient_by_purpose_by_parent_2012\"",
"country-year/warehouse/multilateral_profile/recipient_by_sector_by_di_id.csv" : "multilateral_profile.\"recipient_by_sector_by_di_id_2012\"",
"country-year/warehouse/multilateral_profile/recipient_by_sector_by_parent.csv" : "multilateral_profile.\"recipient_by_sector_by_parent_2012\"",
"country-year/warehouse/multilateral_profile/sector_by_purpose_by_di_id.csv": "multilateral_profile.\"sector_by_purpose_by_di_id_2012\"",
"country-year/warehouse/multilateral_profile/sector_by_purpose_by_parent.csv": "multilateral_profile.\"sector_by_purpose_by_parent_2012\"",
"country-year/warehouse/multilateral_profile/sector_trend.csv": "multilateral_profile.\"sector_trend_2012\""
 // "country-year/displacement.csv" : "data_series.\"displacement\"",
 // "country-year/forgotten_crisis.csv" : "data_series.\"forgotten_crisis\"",
 // "country-year/number_of_un_appeals.csv" : "data_series.\"number_of_un_appeals\"", 
}

